# Setup
title: Poole Tweak
tagline: Tweaking the Template
url: https://akmolteni.github.io/gp
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  
sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
    name: AK Molteni
    url: https://github.com/akmolteni/gp
    email: example@example.com

# Custom vars
version: 2024.08.04

# For github pages
website: https://akmolteni.github.io
baseurl: /gp

